spring:
  profiles:
    active: dev
  cloud:
    gateway:
      default-filters:
      - name: RequestTime
        args:
          withParams: false
      routes:
        - id: mitail-user
          uri: lb://mitail-user
          predicates:
            - Path=/f/**
          filters:
            - StripPrefix=1
        - id: mitail-test
          uri: lb://mitail-test
          predicates:
            - Path=/t/**
          filters:
            - RewritePath=/t/(?<segment>.*), /$\{segment}
#        - id: host_route
#            uri: http://httpbin.org:80/get
#            predicates:
#              - Host=**.fangzhipeng.com #请求头中含有Host为fangzhipeng.com的请求将会被路由转发转发到配置的uri
#              - Method=GET #所有的GET类型的请求都会路由转发到配置的uri


logging:
  config: classpath:logback-boot.xml

feign:
  httpclient:
    enabled: true
  client:
    default:
      connectTimeout: 60000
      readTimeout: 60000

ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 3 #对当前实例的重试次数
  ServerListRefreshInterval: 5000

---
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: elapse_route
#          uri: lb://mitail-user
##          uri: http://httpbin.org:80/get
#          predicates:
#            - Path=/f/**
#          filters:
#            - RewritePath=/f/(?<segment>.*), /$\{segment}
#  profiles: elapse_route
